### ISSUE TITLE
Add "attic" link to category tabs

### ISSUE THREAD

**Issue by EHJ-52n** [52North/52north.github.io#7]
Please add a link to an external page to the list of categories with the following specification:

- link label: attic
- link target: 52north.org/attic/
- link icon: glyphicon glyphicon-new-window from https://getbootstrap.com/docs/3.3/components/#glyphicons-glyphs
- styling: `margin-left: 40px;` in addition to normal tab styling
- the attic link should be the last in the list of tabs; see example screenshot below:
![attic-link](https://user-images.githubusercontent.com/3839896/31606959-e09eae4e-b26a-11e7-83db-536364043c83.png)

**Comment by janschulte** [comment]
Added
